### ISSUE TITLE
Can't replicate random forest model

### ISSUE THREAD

**Issue by EmanuelCastanho** [marine-debris/marine-debris.github.io#5]
I am trying to replicate the Random Forest model that uses Spectral Signatures and Spectral Indices, but I am unable to achieve the same recall (Pixel Accuracy) results.

I noticed that the results can change between Python versions depending on the packages, so I am using the same environment provided by your yml.
My hyper-parameters are the same (including seed), I am also using the weights calculated from Confidence and Water Super Class. I am using the provided dataset.h5 and dataset_si.h5.

These are my results:
![results_hdf](https://user-images.githubusercontent.com/69935277/217027613-608b7610-9a89-4e3f-967b-a08fb3bf9e3f.png)

As you can see, recall is slightly different from your PA results:
`1: 0.92; 2: 0.93; 3: 0.92; 4: 0.27; 5: 0.7; 6: 0.82; 7: 0.83; 8: 1; 9: 0.48; 10: 0.83; 11: 0.33`

Do you know what can be causing this, since the seeds and data are all the same? 

Thank you!

**Comment by Zhanarik** [comment]
Hello everyone, 
I was trying to run random forest. This process took me one day, still can't achieve the dataset. 
**python engineering_patches.py --type texture** 

Tried several times, it just keeps running without any information. 

Wanted to download from the l[ink](https://pithos.okeanos.grnet.gr/public/7Xm6x2uSBHTknNv7vaqgS6), but the link seems broken. Could you please have a look? 
<img width="876" alt="Screen Shot 2023-02-16 at 16 33 21" src="https://user-images.githubusercontent.com/43060102/219340904-4e55fc29-94ee-4a09-a6b2-e5b6e66afd24.png">

**Comment by EmanuelCastanho** [comment]
Hi @Zhanarik ,
This step 2 takes a lot of time, but you have a progress bar that informs you.
I have the `texture` folder saved on my computer, but it is quite heavy to send (3GB).

Please create a new issue about your problem, I will close this one because I [solved](https://machinelearningmastery.com/different-results-each-time-in-machine-learning/) my issue.

**Comment by Zhanarik** [comment]
Hi @EmanuelCastanho, 
I'm very glad that you found the answer for your question. 

Thank you for notifying me.
